from collections import namedtuple

DataProvider = namedtuple('DataProvider', 'code oai_url mdprefix oai_sets')

OAI_DICT = {
    'brockway': DataProvider('brockway',
                             'https://repox.library.miami.edu/repox/OAIHandler',
                             'oai_dc',
                             ['fiu_bml']),
    'coral_gables': DataProvider('coral_gables',
                                 'https://repox.library.miami.edu/repox/OAIHandler',
                                 'oai_dc',
                                 ['fiu_cgm']),
    'fgcu': DataProvider('fgcu',
                        'https://repox.library.miami.edu/repox/OAIHandler',
                        'mods',
                        ['fgcu_020306', 'fgcu_0217']),
    'fiu': DataProvider('fiu',
                        'https://repox.library.miami.edu/repox/OAIHandler',
                        'oai_dc',
                        ['fiu_bzs', 'fiu_civil', 'fiu_dad', 'fiu_doc',
                         'fiu_fls', 'fiu_gbc', 'fiu_glows', 'fiu_iif',
                         'fiu_jng', 'fiu_lgcf', 'fiu_llsm', 'fiu_lter',
                         'fiu_mca', 'fiu_phc', 'fiu_ps', 'fiu_rcp', 'fiu_rte',
                         'fiu_serc', 'fiu_sfnrc', 'fiu_sfwmd', 'fiu_spdloc',
                         'fiu_two', 'fiu_ua', 'fiu_vms', 'fiu_zoo']),
#    'fsu': DataProvider('fsu',
#                        'https://fsu.digital.flvc.org/oai2',
#                        'mods',
#                        ['fsu_digital_library']),
    'gnmhs': DataProvider('gnmhs',
                          'https://repox.library.miami.edu/repox/OAIHandler',
                          'oai_dc',
                          ['fiu_ignmhs']),
    'ir_fiu': DataProvider('ir_fiu',
                           'https://repox.library.miami.edu/repox/OAIHandler',
                           'qdc',
                           ['fiu_chue', 'fiu_crivideo', 'fiu_cuba_poll',
                            'fiu_ecohumanities', 'fiu_ecohumanities_images',
                            'fiu_economics_ops', 'fiu_economics_wps',
                            'fiu_ecxdpeb', 'fiu_etd', 'fiu_fce_lter_photos',
                            'fiu_fce_lter_proposals', 'fiu_fiu_images',
                            'fiu_fiu_video', 'fiu_fiuinview',
                            'fiu_frostcatalogs', 'fiu_laccops', 'fiu_laccopsd',
                            'fiu_laccwps', 'fiu_mpo_broward', 'fiu_mpo_dade',
                            'fiu_mpo_palmbeach', 'fiu_research_reports',
                            'fiu_sercrp', 'fiu_sgabbc_images',
                            'fiu_spain_videos', 'fiu_theatre_images',
                            'fiu_theatre_posters', 'fiu_theatre_programs',
                            'fiu_yearbooks']),
    'mbvm': DataProvider('mbvm',
                         'https://repox.library.miami.edu/repox/OAIHandler',
                         'oai_dc',
                         ['fiu_mbvm']),
    'mcpl': DataProvider('mcpl',
                         'https://repox.library.miami.edu/repox/OAIHandler',
                         'oai_dc',
                         ['fiu_mile']),
    'mdpl': DataProvider('mdpl',
                         'https://repox.library.miami.edu/repox/OAIHandler',
                         'oai_qdc',
                         ['mdpl_o17273coll13', 'mdpl_p17273coll1',
                          'mdpl_p17273coll11', 'mdpl_p17273coll2',
                          'mdpl_p17273coll3', 'mdpl_p17273coll4',
                          'mdpl_p17273coll5', 'mdpl_p17273coll6',
                          'mdpl_p17273coll7', 'mdpl_p17273coll8',
                          'mdpl_p17273coll9']),
    'um': DataProvider('um',
                       'https://repox.library.miami.edu/repox/OAIHandler',
                       'oai_qdc',
                       ['um_5314', 'um_arc5100', 'um_arc5200', 'um_arc5300',
                        'um_arcdigital', 'um_asm0015', 'um_asm0034',
                        'um_asm0037', 'um_asm0038', 'um_asm0055', 'um_asm0060',
                        'um_asm0075', 'um_asm0085', 'um_asm0179', 'um_asm0216',
                        'um_asm0261', 'um_asm0286', 'um_asm0299', 'um_asm0300',
                        'um_asm0301', 'um_asm0304', 'um_asm0341', 'um_asm0344',
                        'um_asm0383', 'um_asm0400', 'um_asm0409', 'um_asm0410',
                        'um_asm0447', 'um_asm0471', 'um_asm0491', 'um_asm0530',
                        'um_asm0566', 'um_asm0567', 'um_asm0569', 'um_asm0570',
                        'um_asm0610', 'um_asm0636', 'um_asm0650', 'um_asm0655',
                        'um_asm0656', 'um_asm0713', 'um_asm5000', 'um_asu0017',
                        'um_asu0281', 'um_asu0651', 'um_asu0654', 'um_chc0015',
                        'um_chc0111', 'um_chc0124', 'um_chc0126', 'um_chc0170',
                        'um_chc0184', 'um_chc0189', 'um_chc0193', 'um_chc0218',
                        'um_chc0219', 'um_chc0336', 'um_chc0339', 'um_chc0347',
                        'um_chc0356', 'um_chc0359', 'um_chc0364', 'um_chc0380',
                        'um_chc0398', 'um_chc0400', 'um_chc0460', 'um_chc0468',
                        'um_chc0484', 'um_chc0487', 'um_chc5006', 'um_chc5010',
                        'um_chc5017', 'um_chc5047', 'um_chc5061O', 'um_chc5066',
                        'um_chc5122', 'um_chc5123', 'um_chc5143', 'um_chc5209',
                        'um_chc5212', 'um_chc5223', 'um_chc5252', 'um_chc5260',
                        'um_chc5277', 'um_chc5278', 'um_chc5298J', 'um_chc5299',
                        'um_chc5312H', 'um_chc5313', 'um_chc5324', 'um_chc5330',
                        'um_chc5352', 'um_chc5372', 'um_chc5376', 'um_chc9999',
                        'um_cubanlaw', 'um_cubanphotos', 'um_dplaper',
                        'um_oralhistory', 'um_pamphlets', 'um_rinhart',
                        'um_rsmasphotos', 'um_ruston', 'um_scbooks',
                        'um_students', 'um_sutherland', 'um_swingle',
                        'um_theater', 'um_tobaccoart', 'um_umathletics',
                        'um_umcolleges', 'um_umevents', 'um_umiscel',
                        'um_umpeople', 'um_umphotos', 'um_umservice',
                        'um_umstudents', 'um_umsupport', 'um_wtswingle']),
    'usf': DataProvider('usf',
                        'http://digital.lib.usf.edu/SobekCM_oai.aspx',
                        'oai_dc',
                        ['cape-canaveral-3d', 'hadobson-papers', 'ohp-ybor',
                         'snaps', 'alicia', 'allsportslibrary', 'yorkunas',
                         'americanindianweekly', 'slaymakera',
                         'army-navy-weekly', 'elaudaz', 'audubonfl', 'tavernier',
                         'beadle-boys', 'brahman', 'braveandbold',
                         'buffalobillstories', 'burgert', 'ohp-carltonanthony',
                         'catesby', 'ohp-celtic', 'cedr', 'centroasturiano-mbrs',
                         'ringlingfamily', 'childrens-lit', 'fl-local-histories',
                         'columbia-gonzmart', 'ohp-columbia', 'ohp-liberators',
                         'cubanrevolutionaries', 'his-dave-porter',
                         'deadwooddicklibrary', 'diamonddickjr']),
    'vhlf': DataProvider('vhlf',
                         'https://repox.library.miami.edu/repox/OAIHandler',
                         'oai_dc',
                         ['fiu_hco'])
}

OUT_PATH = 'D:\\Users\\Roland\\citrus_test\\'
